from __future__ import annotations

import asyncio
import base64
import io
import random
import struct
import tempfile
import uuid
import logging
from concurrent.futures import ProcessPoolExecutor
from typing import Any, Callable

import numpy as np
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from pydantic import BaseModel

import json as _json
import functools
from typing import cast

import latentscore as ls
from latentscore.models import _heuristic_config, FastEmbeddingModel, FastHeavyModel, ExampleConfig
from latentscore.config import (
    MusicConfig, MusicConfigPrompt,
    melody_density_to_float, syncopation_to_float, swing_to_float,
    motif_repeat_to_float, step_bias_to_float, chromatic_to_float,
    cadence_to_float, chord_change_to_bars,
)
from latentscore.synth import assemble
from pydantic import ValidationError as _ValidationError

import laion_clap

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("latentscore-api")

# ─── Label→numeric converters for LLM-generated configs ─────────────────────
_LABEL_CONVERTERS: dict[str, Callable[[str], float | int]] = {
    "melody_density": melody_density_to_float,
    "syncopation": syncopation_to_float,
    "swing": swing_to_float,
    "motif_repeat_prob": motif_repeat_to_float,
    "step_bias": step_bias_to_float,
    "chromatic_prob": chromatic_to_float,
    "cadence_strength": cadence_to_float,
    "chord_change_bars": chord_change_to_bars,
}

def _coerce_config(raw: dict[str, Any]) -> MusicConfig:
    """Convert LLM config (may have enum labels) into MusicConfig (needs floats).

    Robust against LLMs inventing values — strips any field that fails validation.
    """
    data = dict(raw)
    for field, converter in _LABEL_CONVERTERS.items():
        if field in data and isinstance(data[field], str):
            try:
                data[field] = converter(data[field])
            except Exception:
                del data[field]  # let MusicConfig use its default
    # Clamp integer fields to valid ranges
    if "density" in data:
        try:
            data["density"] = max(2, min(6, int(data["density"])))
        except (ValueError, TypeError):
            del data["density"]
    if "phrase_len_bars" in data:
        try:
            v = int(data["phrase_len_bars"])
            data["phrase_len_bars"] = min((2, 4, 8), key=lambda x: abs(x - v))
        except (ValueError, TypeError):
            del data["phrase_len_bars"]
    schema_fields = set(MusicConfig.model_fields.keys())
    filtered = {k: v for k, v in data.items() if k in schema_fields}
    # Try validation; on failure, strip offending fields one at a time
    while True:
        try:
            return MusicConfig.model_validate(filtered)
        except _ValidationError as exc:
            bad_fields = {e["loc"][0] for e in exc.errors() if e.get("loc")}
            if not bad_fields:
                return MusicConfig()  # give up, use all defaults
            for f in bad_fields:
                filtered.pop(f, None)
                logger.warning("Stripped invalid LLM field %s", f)


app = FastAPI(title="LatentScore Live", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─── Process pool for CPU-bound DSP synthesis ────────────────────────────────
# The DSP synth (assemble()) is CPU-bound NumPy work. Python's GIL means
# threads cannot truly parallelize CPU work. ProcessPoolExecutor spawns real
# OS processes with their own GIL for true parallel execution.
synth_pool = ProcessPoolExecutor(max_workers=4)


# ─── Enriched embedding model ────────────────────────────────────────────────
# Subclasses FastEmbeddingModel to also return the title and palettes stored
# alongside each config in the embed map JSONL (generated by LLMs during
# training data creation).

class _VibeResult:
    """Result from vibe_to_config: config + optional metadata from the embed map."""
    __slots__ = ("config", "title", "palettes")

    def __init__(
        self,
        config: MusicConfig,
        title: str | None = None,
        palettes: list[dict[str, Any]] | None = None,
    ):
        self.config = config
        self.title = title
        self.palettes = palettes


class EnrichedFastModel(FastEmbeddingModel):
    """FastEmbeddingModel that also captures title and palettes from the embed map."""

    def __init__(self) -> None:
        super().__init__()
        self._row_titles: list[str | None] = []
        self._row_palettes: list[list[dict[str, Any]] | None] = []

    @functools.lru_cache(maxsize=1)
    def _embed_map_examples(self) -> tuple[tuple[ExampleConfig, ...], np.ndarray | None]:
        """Override to also capture title and palettes per row."""
        from latentscore.models import _fast_track_examples

        map_path = self._resolve_embed_map_path()
        if map_path is None or not map_path.exists():
            fallback = _fast_track_examples()
            self._row_titles = [None] * len(fallback)
            self._row_palettes = [None] * len(fallback)
            return fallback, None

        examples: list[ExampleConfig] = []
        embeddings: list[list[float]] = []
        titles: list[str | None] = []
        palettes: list[list[dict[str, Any]] | None] = []

        try:
            with map_path.open("r", encoding="utf-8") as handle:
                for line in handle:
                    if not line.strip():
                        continue
                    try:
                        row = _json.loads(line)
                    except _json.JSONDecodeError:
                        continue
                    if self._exclude_splits and row.get("split") in self._exclude_splits:
                        continue
                    vibe = row.get("vibe_original") or row.get("vibe") or row.get("vibe_noisy")
                    config_data = row.get("config")
                    if not vibe or not isinstance(config_data, dict):
                        continue
                    try:
                        prompt_config = MusicConfigPrompt.model_validate(config_data)
                        music_config = prompt_config.to_config()
                    except _ValidationError:
                        try:
                            music_config = MusicConfig.model_validate(config_data)
                        except _ValidationError:
                            continue
                    examples.append(ExampleConfig(vibe=str(vibe), config=music_config))
                    titles.append(row.get("title"))
                    palettes.append(row.get("palettes"))
                    embed: object = row.get("embedding")
                    if isinstance(embed, list):
                        embeddings.append([float(v) for v in cast(list[Any], embed)])
        except OSError as exc:
            logger.warning("Failed reading embedding map: %s", exc, exc_info=True)
            fallback = _fast_track_examples()
            self._row_titles = [None] * len(fallback)
            self._row_palettes = [None] * len(fallback)
            return fallback, None

        if not examples:
            fallback = _fast_track_examples()
            self._row_titles = [None] * len(fallback)
            self._row_palettes = [None] * len(fallback)
            return fallback, None

        self._row_titles = titles
        self._row_palettes = palettes

        matrix: np.ndarray | None = None
        if len(embeddings) == len(examples):
            mat = np.asarray(embeddings, dtype=np.float32)
            norms = np.linalg.norm(mat, axis=1, keepdims=True)
            norms[norms == 0] = 1.0
            matrix = mat / norms
        return tuple(examples), matrix

    async def generate_with_meta(self, vibe: str) -> _VibeResult:
        """Generate config + title/palettes in one thread-safe call."""
        try:
            return await asyncio.to_thread(self._select_with_meta, vibe)
        except Exception as exc:
            logger.warning("Fast model fallback: %s", exc, exc_info=True)
            return _VibeResult(_heuristic_config(vibe))

    def _select_with_meta(self, vibe: str) -> _VibeResult:
        encoder = self._load_encoder()
        example_matrix = self._example_matrix()
        query = encoder.encode([vibe], normalize_embeddings=True)
        query_vec = np.asarray(query, dtype=np.float32)[0]
        scores = example_matrix @ query_vec
        best_idx = int(np.argmax(scores))
        config = self._examples()[best_idx].config
        title = self._row_titles[best_idx] if best_idx < len(self._row_titles) else None
        palettes = self._row_palettes[best_idx] if best_idx < len(self._row_palettes) else None
        return _VibeResult(config, title, palettes)


def _palette_from_embed(palettes_data: list[dict[str, Any]]) -> list[str] | None:
    """Convert embed map palette data to 5 hex strings for the frontend.

    The embed map stores 3 palettes of 5 weighted colors each.  We take the
    first palette and reorder by luminance: darkest → position [3] (background),
    brightest → position [4] (accent), rest → [0-2].
    """
    if not palettes_data:
        return None
    colors = palettes_data[0].get("colors", [])
    if len(colors) != 5:
        return None
    hexes = [c.get("hex", "#000000") for c in colors]

    def lum(h: str) -> float:
        try:
            r, g, b = int(h[1:3], 16), int(h[3:5], 16), int(h[5:7], 16)
        except (ValueError, IndexError):
            return 0
        return 0.299 * r + 0.587 * g + 0.114 * b

    by_lum = sorted(range(5), key=lambda i: lum(hexes[i]))
    bg_idx = by_lum[0]       # darkest → background
    accent_idx = by_lum[-1]  # brightest → accent
    mid = [i for i in range(5) if i != bg_idx and i != accent_idx]
    return [hexes[mid[0]], hexes[mid[1]], hexes[mid[2]], hexes[bg_idx], hexes[accent_idx]]


vibe_model: EnrichedFastModel | None = None
fast_heavy_model: FastHeavyModel | None = None
clap_model: laion_clap.CLAP_Module | None = None


@app.on_event("startup")
async def startup_warmup():
    """Load the enriched embedding model, CLAP model, and pre-warm the DSP synth."""
    global vibe_model, fast_heavy_model, clap_model

    logger.info("Loading EnrichedFastModel (with title + palette metadata)...")
    vibe_model = EnrichedFastModel()

    logger.info("Loading FastHeavyModel (CLAP audio-grounded matching)...")
    try:
        fh = FastHeavyModel()
        fh.warmup()
        fast_heavy_model = fh
        logger.info("FastHeavyModel ready.")
    except Exception as exc:
        logger.warning("FastHeavyModel unavailable, fast_heavy will fall back to fast: %s", exc)

    logger.info("Loading CLAP model for audio-text evaluation...")
    clap_model = laion_clap.CLAP_Module(enable_fusion=False)
    clap_model.load_ckpt()

    logger.info("Warming up DSP synth...")
    config = MusicConfig()
    loop = asyncio.get_running_loop()
    await loop.run_in_executor(synth_pool, _render_audio_sync, config, 0.1)
    logger.info("Synth warm-up complete. Ready to serve.")


async def vibe_to_config(vibe: str, model: str = "fast") -> _VibeResult:
    """Convert vibe text → config + optional metadata from the embed map."""
    if model == "fast_heavy" and fast_heavy_model is not None:
        config = await fast_heavy_model.generate(vibe)
        return _VibeResult(config)
    if vibe_model is not None:
        return await vibe_model.generate_with_meta(vibe)
    return _VibeResult(_heuristic_config(vibe))


# ─── Types ───────────────────────────────────────────────────────────────────

PARAM_OPTIONS: dict[str, list[str]] = {
    "tempo": list(ls.TempoLabel.__args__),
    "root": list(ls.RootNote.__args__),
    "mode": list(ls.ModeName.__args__),
    "brightness": list(ls.BrightnessLabel.__args__),
    "space": list(ls.SpaceLabel.__args__),
    "density": ["2", "3", "4", "5", "6"],
    "bass": list(ls.BassStyle.__args__),
    "pad": list(ls.PadStyle.__args__),
    "melody": list(ls.MelodyStyle.__args__),
    "rhythm": list(ls.RhythmStyle.__args__),
    "texture": list(ls.TextureStyle.__args__),
    "accent": list(ls.AccentStyle.__args__),
    "motion": list(ls.MotionLabel.__args__),
    "attack": list(ls.AttackStyle.__args__),
    "stereo": list(ls.StereoLabel.__args__),
    "echo": list(ls.EchoLabel.__args__),
    "human": list(ls.HumanFeelLabel.__args__),
    "grain": list(ls.GrainStyle.__args__),
}


# ─── Color palette generation ────────────────────────────────────────────────
# Mood-aware color theory: mode→hue family, brightness→lightness,
# space→saturation, with analogous primary/secondary and complementary accent.

_MODE_HUES: dict[str, float] = {
    "major": 45,        # warm gold/amber
    "minor": 230,       # deep blue/indigo
    "dorian": 160,      # teal/sage
    "mixolydian": 25,   # sunset orange
}
_BRIGHTNESS_LIGHTNESS: dict[str, float] = {
    "very_dark": 0.18, "dark": 0.28, "medium": 0.42,
    "bright": 0.56, "very_bright": 0.68,
}
_SPACE_SATURATION: dict[str, float] = {
    "dry": 0.65, "small": 0.55, "medium": 0.45, "large": 0.35, "vast": 0.25,
}
_TEMPO_HUE_SHIFT: dict[str, float] = {
    "very_slow": -12, "slow": -6, "medium": 0, "fast": 8, "very_fast": 16,
}
_GRAIN_SAT_MULT: dict[str, float] = {
    "clean": 1.0, "warm": 0.85, "gritty": 0.65,
}


def _vibe_hash(vibe: str) -> float:
    """Deterministic hash of vibe text → [0, 360) degrees."""
    h = 0
    for ch in vibe:
        h = (h * 31 + ord(ch)) & 0xFFFFFFFF
    return (h % 3600) / 10.0


def generate_palette(config: MusicConfig, vibe: str = "") -> list[str]:
    """Generate a 5-color palette using mood-aware color theory."""
    base_h = _MODE_HUES.get(config.mode, 200)
    vibe_offset = (_vibe_hash(vibe) % 50) - 25  # ±25° per-vibe uniqueness
    tempo_shift = _TEMPO_HUE_SHIFT.get(config.tempo, 0)
    h = (base_h + vibe_offset + tempo_shift) % 360

    l_base = _BRIGHTNESS_LIGHTNESS.get(config.brightness, 0.42)
    s_base = _SPACE_SATURATION.get(config.space, 0.45)
    s_base *= _GRAIN_SAT_MULT.get(config.grain, 1.0)

    return [
        # Primary: base mood color
        _hsl_to_hex(h, s_base + 0.10, l_base),
        # Secondary: analogous hue, slightly lighter
        _hsl_to_hex((h + 30) % 360, s_base, l_base * 0.85 + 0.10),
        # Tertiary: split-complementary, desaturated
        _hsl_to_hex((h + 180) % 360, s_base * 0.55, l_base * 0.70 + 0.12),
        # Background: very dark with hint of primary hue
        _hsl_to_hex(h, s_base * 0.30, 0.06),
        # Accent: high-saturation complementary pop
        _hsl_to_hex(
            (h + 160) % 360,
            min(0.85, s_base + 0.30),
            min(0.70, l_base + 0.18),
        ),
    ]


def _hsl_to_hex(h: float, s: float, l: float) -> str:
    h = h / 360.0
    s = max(0, min(1, s))
    l = max(0, min(1, l))
    if s == 0:
        r = g = b = l
    else:
        def hue2rgb(p: float, q: float, t: float) -> float:
            if t < 0: t += 1
            if t > 1: t -= 1
            if t < 1/6: return p + (q - p) * 6 * t
            if t < 1/2: return q
            if t < 2/3: return p + (q - p) * (2/3 - t) * 6
            return p
        q = l * (1 + s) if l < 0.5 else l + s - l * s
        p = 2 * l - q
        r = hue2rgb(p, q, h + 1/3)
        g = hue2rgb(p, q, h)
        b = hue2rgb(p, q, h - 1/3)
    return f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"


# ─── Title generation ────────────────────────────────────────────────────────
# Uses the actual vibe text instead of random word dictionaries.

_STOP_WORDS = frozenset({
    "a", "an", "the", "in", "on", "at", "to", "for", "of", "with",
    "and", "or", "but", "is", "was", "are", "it", "its", "my", "your",
    "from", "by", "as", "like", "very", "really", "just", "some", "that",
    "this", "over", "into", "through", "about",
})

_MODE_ADJECTIVES: dict[str, list[str]] = {
    "major": ["Golden", "Radiant", "Luminous", "Sunlit", "Bright"],
    "minor": ["Moonlit", "Veiled", "Twilight", "Dusted", "Shadowed"],
    "dorian": ["Ancient", "Sage", "Woven", "Mystic", "Verdant"],
    "mixolydian": ["Amber", "Wandering", "Drifting", "Hazy", "Burnished"],
}


def generate_title(vibe: str, config: MusicConfig) -> str:
    """Generate a title from the vibe text, falling back to config-derived words."""
    words = [w.strip(",.!?;:\"'()[]") for w in vibe.split()]
    meaningful = [w for w in words if w.lower() not in _STOP_WORDS and len(w) > 2]

    if len(meaningful) >= 2:
        return " ".join(w.capitalize() for w in meaningful[:4])[:60]

    # Short vibe: prepend a mode-derived adjective
    rng = random.Random(hash(vibe) % 2**32)
    adj = rng.choice(_MODE_ADJECTIVES.get(config.mode, ["Untitled"]))
    if meaningful:
        return f"{adj} {meaningful[0].capitalize()}"[:60]
    return f"{adj} Soundscape"[:60]


# ─── Justification generation ────────────────────────────────────────────────
# Natural prose connecting the vibe to sonic choices.

_MODE_FEELING: dict[str, str] = {
    "major": "bright and uplifting",
    "minor": "deep and emotional",
    "dorian": "mystical and modal",
    "mixolydian": "warm and adventurous",
}
_TEMPO_FEELING: dict[str, str] = {
    "very_slow": "glacial, meditative pace",
    "slow": "contemplative, unhurried flow",
    "medium": "balanced, steady movement",
    "fast": "driven, energetic pulse",
    "very_fast": "intense, urgent momentum",
}
_SPACE_FEELING: dict[str, str] = {
    "dry": "intimate, close-up presence",
    "small": "cozy, contained warmth",
    "medium": "natural room ambience",
    "large": "expansive, open atmosphere",
    "vast": "cathedral-like, infinite space",
}


def generate_justification(vibe: str, config: MusicConfig) -> str:
    """Generate a natural-sounding explanation of the sonic choices."""
    feeling = _MODE_FEELING.get(config.mode, "balanced")
    pace = _TEMPO_FEELING.get(config.tempo, "moderate movement")
    room = _SPACE_FEELING.get(config.space, "natural space")

    texture_desc = (
        f" through {config.texture.replace('_', ' ')} textures"
        if config.texture != "none" else ""
    )
    depth_desc = " Sub-bass reinforcement adds physical weight." if config.depth else ""

    return (
        f'"{vibe}" suggests a {feeling} soundscape. '
        f"{config.root.upper()} {config.mode} provides the harmonic foundation "
        f"with a {pace}. "
        f"A {config.bass.replace('_', ' ')} bass line and "
        f"{config.pad.replace('_', ' ')} pad build the harmonic bed, "
        f"while {config.melody.replace('_', ' ')} melody "
        f"adds movement{texture_desc}. "
        f"The spatial character is {room} with {config.echo} delay "
        f"and {config.stereo.replace('_', ' ')} stereo spread.{depth_desc}"
    )


# ─── Presets ─────────────────────────────────────────────────────────────────

PRESETS = [
    # Mix of familiar scene presets (predictable) and diversity-sampled
    # high-CLAP vibes from the GRPO split (sonically distinct, surprising).
    # ── Familiar ──
    {"id": "deep-ocean", "name": "Deep Ocean",
     "description": "Dark ambient underwater cave with bioluminescence",
     "vibe": "dark ambient underwater cave with bioluminescence", "icon": "ocean"},
    {"id": "frozen-memory", "name": "Frozen Memory",
     "description": "Nostalgic winter reverence, stillness in the frost",
     "vibe": "nostalgic winter reverence", "icon": "frost"},
    {"id": "zen", "name": "Zen Garden",
     "description": "Peaceful meditation in a zen garden at dawn",
     "vibe": "peaceful meditation in a zen garden", "icon": "zen"},
    {"id": "space", "name": "Deep Space",
     "description": "Floating through the cosmos, stars drifting past",
     "vibe": "floating through deep space surrounded by stars cosmic ambient", "icon": "space"},
    {"id": "midnight-rain", "name": "Midnight Rain",
     "description": "Stillness before the storm, dark anticipation building",
     "vibe": "The scene captures the stillness before the storm.", "icon": "rain"},
    # ── Diversity-sampled high-CLAP (GRPO split) ──
    {"id": "respect-mystery", "name": "Respect Mystery",
     "description": "Reverence for the unknowable and unseen",
     "vibe": "Respect mystery.", "icon": "mystery"},
    {"id": "treasured-object", "name": "Treasured Object",
     "description": "Tension simmering around something precious",
     "vibe": "Tension over a treasured object.", "icon": "tension"},
    {"id": "bittersweetness", "name": "Bittersweetness",
     "description": "A warm ache that slowly fills the room",
     "vibe": "Bittersweetness spreads.", "icon": "bittersweet"},
    {"id": "stars-and-shore", "name": "Stars & Shore",
     "description": "Celestial wonder mixed with ocean longing",
     "vibe": "Stars lesson and beach yearning.", "icon": "stars"},
    {"id": "final-thanks", "name": "Final Thanks",
     "description": "Gratitude and warmth as things come to a close",
     "vibe": "Final thanks and optimism.", "icon": "thanks"},
    {"id": "healing-music", "name": "Healing Music",
     "description": "Celestial serenity, gentle and restorative",
     "vibe": "healing music", "icon": "healing"},
    {"id": "cyberpunk", "name": "Neon City",
     "description": "Cyberpunk nightclub in Tokyo with neon-soaked streets",
     "vibe": "cyberpunk nightclub in tokyo", "icon": "city"},
]


# ─── Active Sessions ─────────────────────────────────────────────────────────

class ActiveSession:
    def __init__(self, session_id: str, config: MusicConfig, vibe: str):
        self.session_id = session_id
        self.config = config
        self.vibe = vibe
        self.active_ws_id: str | None = None

    def update_config(self, updates: dict[str, Any]) -> MusicConfig:
        current = self.config.model_dump()
        for key, value in updates.items():
            if key in current:
                if key == "density":
                    value = int(value)
                current[key] = value
        self.config = MusicConfig.model_validate(current)
        return self.config


sessions: dict[str, ActiveSession] = {}


# ─── REST Endpoints ──────────────────────────────────────────────────────────

@app.get("/api/health")
async def health():
    return {"status": "ok"}


@app.get("/api/presets")
async def get_presets():
    return {"presets": PRESETS}


@app.get("/api/param-options")
async def get_param_options():
    return {"options": PARAM_OPTIONS}


@app.get("/api/capabilities")
async def get_capabilities():
    models = ["fast"]
    if fast_heavy_model is not None:
        models.append("fast_heavy")
    return {"models": models, "expressive_available": False}


class GenerateRequest(BaseModel):
    vibe: str
    duration: float = 8.0
    model: str = "fast"


class GenerateResponse(BaseModel):
    session_id: str
    title: str
    justification: str
    palette: list[str]
    config: dict[str, Any]


@app.post("/api/generate", response_model=GenerateResponse)
async def generate_config(req: GenerateRequest):
    result = await vibe_to_config(req.vibe, req.model)
    session_id = str(uuid.uuid4())[:8]
    session = ActiveSession(session_id, result.config, req.vibe)
    sessions[session_id] = session

    # Use embed-map metadata when available, fall back to heuristic
    embed_palette = _palette_from_embed(result.palettes) if result.palettes else None

    return GenerateResponse(
        session_id=session_id,
        title=result.title or generate_title(req.vibe, result.config),
        justification=generate_justification(req.vibe, result.config),
        palette=embed_palette or generate_palette(result.config, req.vibe),
        config=result.config.model_dump(),
    )


# ─── Create Session from Client-Provided Config ─────────────────────────────
# The frontend calls the user's LLM directly (API key never leaves the browser),
# then sends the resulting config here to create a playable session.

class CreateFromConfigRequest(BaseModel):
    vibe: str
    config: dict[str, Any]
    justification: str = ""
    title: str | None = None
    palette: list[str] | None = None


@app.post("/api/create-from-config", response_model=GenerateResponse)
async def create_from_config(req: CreateFromConfigRequest):
    """Create a session from a pre-built config (generated client-side by user's LLM)."""
    config = _coerce_config(req.config)

    session_id = str(uuid.uuid4())[:8]
    session = ActiveSession(session_id, config, req.vibe)
    sessions[session_id] = session

    # Use LLM-generated title/palette if provided, fall back to heuristic
    title = req.title or generate_title(req.vibe, config)
    palette = req.palette if req.palette and len(req.palette) == 5 else generate_palette(config, req.vibe)

    return GenerateResponse(
        session_id=session_id,
        title=title,
        justification=req.justification or generate_justification(req.vibe, config),
        palette=palette,
        config=config.model_dump(),
    )


class UpdateParamsRequest(BaseModel):
    session_id: str
    updates: dict[str, Any]


@app.post("/api/update-params")
async def update_params(req: UpdateParamsRequest):
    session = sessions.get(req.session_id)
    if not session:
        return {"error": "Session not found"}

    new_config = session.update_config(req.updates)
    palette = generate_palette(new_config, session.vibe)
    title = generate_title(session.vibe, new_config)
    return {"config": new_config.model_dump(), "palette": palette, "title": title}


# ─── CLAP Best-of-N Selection ─────────────────────────────────────────────────


def _cosine_sim(a: np.ndarray, b: np.ndarray) -> float:
    """Cosine similarity between two vectors (or batches)."""
    a = a.flatten()
    b = b.flatten()
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-8))


class CandidateConfig(BaseModel):
    config: dict[str, Any]
    justification: str = ""
    title: str | None = None
    palette: list[str] | None = None


class SelectBestRequest(BaseModel):
    vibe: str
    candidates: list[CandidateConfig]


@app.post("/api/select-best-config", response_model=GenerateResponse)
async def select_best_config(req: SelectBestRequest):
    """Render audio for each candidate config, CLAP-score against vibe, return best."""
    if not clap_model:
        raise ValueError("CLAP model not loaded")
    if not req.candidates:
        raise ValueError("No candidates provided")

    # Validate all configs — coerce LLM enum labels to numeric values
    configs: list[MusicConfig] = []
    for c in req.candidates:
        configs.append(_coerce_config(c.config))

    # Render 30s audio for each candidate in parallel
    loop = asyncio.get_running_loop()
    render_tasks = [
        loop.run_in_executor(synth_pool, _render_audio_sync, cfg, 30.0)
        for cfg in configs
    ]
    wav_bytes_list = await asyncio.gather(*render_tasks)

    # Write temp WAV files for CLAP (it needs file paths)
    tmp_paths: list[str] = []
    try:
        for i, wav_bytes in enumerate(wav_bytes_list):
            tmp = tempfile.NamedTemporaryFile(suffix=".wav", delete=False)
            tmp.write(wav_bytes)
            tmp.close()
            tmp_paths.append(tmp.name)

        # CLAP scoring
        text_embed = clap_model.get_text_embedding([req.vibe])
        audio_embeds = clap_model.get_audio_embedding_from_filelist(tmp_paths)

        scores = [_cosine_sim(audio_embeds[i], text_embed[0]) for i in range(len(tmp_paths))]
        best_idx = int(np.argmax(scores))

        logger.info(
            f"CLAP scores for '{req.vibe[:40]}': "
            + ", ".join(f"[{i}]={s:.4f}" for i, s in enumerate(scores))
            + f" → winner: [{best_idx}]"
        )
    finally:
        import os
        for p in tmp_paths:
            try:
                os.unlink(p)
            except OSError:
                pass

    # Create session for the winning candidate
    winner = req.candidates[best_idx]
    winner_config = configs[best_idx]
    session_id = str(uuid.uuid4())[:8]
    session = ActiveSession(session_id, winner_config, req.vibe)
    sessions[session_id] = session

    title = winner.title or generate_title(req.vibe, winner_config)
    palette = winner.palette if winner.palette and len(winner.palette) == 5 else generate_palette(winner_config, req.vibe)

    return GenerateResponse(
        session_id=session_id,
        title=title,
        justification=winner.justification or generate_justification(req.vibe, winner_config),
        palette=palette,
        config=winner_config.model_dump(),
    )


# ─── DSP Rendering ───────────────────────────────────────────────────────────


def _float_array_to_wav(
    samples: np.ndarray, sample_rate: int = ls.SAMPLE_RATE
) -> bytes:
    """Encode float32 numpy samples → WAV bytes."""
    samples = np.clip(samples, -1.0, 1.0)
    buf = io.BytesIO()
    n_samples = len(samples)
    data_size = n_samples * 2
    buf.write(b"RIFF")
    buf.write(struct.pack("<I", 36 + data_size))
    buf.write(b"WAVEfmt ")
    buf.write(struct.pack("<IHHIIHH", 16, 1, 1, sample_rate, sample_rate * 2, 2, 16))
    buf.write(b"data")
    buf.write(struct.pack("<I", data_size))
    buf.write((samples * 32767).astype(np.int16).tobytes())
    return buf.getvalue()


def _render_audio_sync(config: MusicConfig, duration: float = 60.0) -> bytes:
    """Render full audio → WAV bytes. Runs in a subprocess."""
    internal = config.to_internal()
    samples = assemble(internal, duration=duration)
    return _float_array_to_wav(np.asarray(samples, dtype=np.float32))


# ─── Full Render Endpoint ───────────────────────────────────────────────────


@app.get("/api/render/{session_id}")
async def render_audio(session_id: str, duration: float = 60.0):
    """Render full audio for a session, return WAV bytes."""
    session = sessions.get(session_id)
    if not session:
        return Response(content="Session not found", status_code=404)

    duration = min(duration, 300.0)  # cap at 5 minutes
    loop = asyncio.get_running_loop()
    wav_bytes = await loop.run_in_executor(
        synth_pool, _render_audio_sync, session.config, duration
    )
    return Response(content=wav_bytes, media_type="audio/wav")


# ─── WebSocket Live Streaming (phase-continuous via ls.live) ─────────────────


@app.websocket("/ws/stream/{session_id}")
async def websocket_stream(websocket: WebSocket, session_id: str):
    await websocket.accept()

    session = sessions.get(session_id)
    if not session:
        await websocket.send_json({"type": "error", "message": "Session not found"})
        await websocket.close()
        return

    ws_id = str(uuid.uuid4())[:8]
    session.active_ws_id = ws_id
    chunk_duration = 2.0

    logger.info(f"Starting live stream for session {session_id} (ws={ws_id})")

    stopped = False

    async def receive_messages():
        nonlocal stopped
        try:
            while not stopped:
                msg = await websocket.receive_json()
                if msg.get("type") == "stop":
                    stopped = True
                    break
        except (WebSocketDisconnect, Exception):
            stopped = True

    recv_task = asyncio.create_task(receive_messages())
    stream = ls.live(session.config, chunk_seconds=chunk_duration)

    try:
        async for chunk in stream.achunks(seconds=600):
            if stopped or session.active_ws_id != ws_id:
                break

            wav_bytes = _float_array_to_wav(chunk)
            b64 = base64.b64encode(wav_bytes).decode("ascii")
            await websocket.send_json({
                "type": "audio_chunk",
                "data": b64,
                "duration": chunk_duration,
            })

    except WebSocketDisconnect:
        logger.info(f"Client disconnected from session {session_id} (ws={ws_id})")
    except Exception as e:
        logger.error(f"Stream error: {e}")
        try:
            await websocket.send_json({"type": "error", "message": str(e)})
        except Exception:
            pass
    finally:
        stream.close()
        recv_task.cancel()
        if session.active_ws_id == ws_id:
            session.active_ws_id = None
        logger.info(f"Live stream ended for session {session_id} (ws={ws_id})")


# ─── Playlist Endpoints ─────────────────────────────────────────────────────

class PlaylistTrack(BaseModel):
    vibe: str
    duration: float = 30.0
    model: str = "fast"


class PlaylistRequest(BaseModel):
    name: str
    tracks: list[PlaylistTrack]


@app.post("/api/playlist/create")
async def create_playlist(req: PlaylistRequest):
    results = []
    for track in req.tracks:
        result = await vibe_to_config(track.vibe, track.model)
        session_id = str(uuid.uuid4())[:8]
        sessions[session_id] = ActiveSession(session_id, result.config, track.vibe)
        embed_palette = _palette_from_embed(result.palettes) if result.palettes else None
        results.append({
            "session_id": session_id,
            "vibe": track.vibe,
            "title": result.title or generate_title(track.vibe, result.config),
            "palette": embed_palette or generate_palette(result.config, track.vibe),
            "justification": generate_justification(track.vibe, result.config),
            "config": result.config.model_dump(),
            "duration": track.duration,
        })
    return {"name": req.name, "tracks": results}


# ─── Static file serving (single-container deploy: Railway, etc.) ────────────
# When built with the root Dockerfile, frontend assets live in ./static/.
# In docker-compose mode, static/ doesn't exist and this block is skipped.

from pathlib import Path as _Path

_STATIC_DIR = _Path(__file__).parent / "static"
if _STATIC_DIR.is_dir():
    from starlette.responses import FileResponse as _FileResponse

    @app.get("/{full_path:path}")
    async def _serve_frontend(full_path: str):
        """Serve built frontend files. SPA fallback to index.html."""
        file_path = (_STATIC_DIR / full_path).resolve()
        if file_path.is_file() and str(file_path).startswith(str(_STATIC_DIR.resolve())):
            return _FileResponse(str(file_path))
        return _FileResponse(str(_STATIC_DIR / "index.html"))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
