"""Common shared definitions for latentscore and data_work."""

from common.music_schema import (
    MAX_LONG_FIELD_CHARS,
    PALETTE_COLOR_DESC,
    PALETTE_DESC,
    PALETTE_WEIGHT_DESC,
    PALETTE_WEIGHT_ORDER,
    PALETTES_DESC,
    PROMPT_DESC,
    PROMPT_REGISTER_MAX,
    PROMPT_REGISTER_MIN,
    AccentStyle,
    AttackStyle,
    BassStyle,
    BrightnessLabel,
    CadenceLabel,
    ChordChangeLabel,
    ChordExtensions,
    ChromaticLabel,
    DensityLevel,
    EchoLabel,
    GrainStyle,
    HarmonyStyle,
    HumanFeelLabel,
    MelodyDensityLabel,
    MelodyEngine,
    MelodyStyle,
    ModeName,
    MotifRepeatLabel,
    MotionLabel,
    MusicConfigPrompt,
    MusicConfigPromptPayload,
    PadStyle,
    Palette,
    PaletteColor,
    PhraseLengthBars,
    RhythmStyle,
    RootNote,
    SpaceLabel,
    StepBiasLabel,
    StereoLabel,
    SwingLabel,
    SyncopationLabel,
    TempoLabel,
    TensionCurve,
    TextureStyle,
    WeightLabel,
    repair_palette_duplicates,
    schema_hash,
    schema_signature,
)
from common.prompt_registry import (
    PromptConfig,
    PromptVersion,
    get_prompt,
    list_prompts,
    register_prompt,
    render_config_prompt,
    render_prompt,
)
from common.prompts import (
    # Output requirements
    OUTPUT_JSON_ONLY,
    OUTPUT_MATCH_SCHEMA,
    OUTPUT_USE_ENUMS,
    OUTPUT_USE_EXAMPLE_KEYS,
    # Palette requirements
    PALETTE_REQUIREMENTS,
    # Core role descriptions
    ROLE_MUSIC_EXPERT,
    ROLE_SOUND_DESIGNER,
    # Style guidance
    STYLE_AMBIENT,
    STYLE_JUSTIFICATION_CONCISE,
    # Task instructions
    TASK_GENERATE_CONFIG,
    TASK_JUSTIFICATION_FIRST,
    TASK_USE_EXAMPLES,
    # Builder functions
    build_expressive_prompt,
    build_inference_prompt,
    build_litellm_prompt,
    build_music_prompt,
    build_training_prompt,
)
from common.reward_config import (
    DEFAULT_REWARD_CONFIG,
    ClapScorerConfig,
    RewardConfig,
    RewardWeights,
    ScorerProtocol,
)
from common.training_config import (
    ABLATION_PRESETS,
    BASE_MODELS,
    DEFAULT_TRAINING_CONFIG,
    BatchConfig,
    DataConfig,
    GRPOConfig,
    InfraConfig,
    LoggingConfig,
    LoRAConfig,
    NoiseConfig,
    OptimizerConfig,
    TrainingConfig,
)

__all__ = [
    # Reward configuration
    "ClapScorerConfig",
    "DEFAULT_REWARD_CONFIG",
    "RewardConfig",
    "RewardWeights",
    "ScorerProtocol",
    # Training configuration
    "ABLATION_PRESETS",
    "BASE_MODELS",
    "BatchConfig",
    "DataConfig",
    "DEFAULT_TRAINING_CONFIG",
    "GRPOConfig",
    "InfraConfig",
    "LoggingConfig",
    "LoRAConfig",
    "NoiseConfig",
    "OptimizerConfig",
    "TrainingConfig",
    # Prompt registry
    "PromptConfig",
    "PromptVersion",
    "get_prompt",
    "list_prompts",
    "register_prompt",
    "render_config_prompt",
    "render_prompt",
    # Schema constants
    "MAX_LONG_FIELD_CHARS",
    "PALETTE_COLOR_DESC",
    "PALETTE_DESC",
    "PALETTE_WEIGHT_DESC",
    "PALETTE_WEIGHT_ORDER",
    "PALETTES_DESC",
    "PROMPT_DESC",
    "PROMPT_REGISTER_MAX",
    "PROMPT_REGISTER_MIN",
    # Schema types
    "AccentStyle",
    "AttackStyle",
    "BassStyle",
    "BrightnessLabel",
    "CadenceLabel",
    "ChordChangeLabel",
    "ChordExtensions",
    "ChromaticLabel",
    "DensityLevel",
    "EchoLabel",
    "GrainStyle",
    "HarmonyStyle",
    "HumanFeelLabel",
    "MelodyDensityLabel",
    "MelodyEngine",
    "MelodyStyle",
    "ModeName",
    "MotifRepeatLabel",
    "MotionLabel",
    "MusicConfigPrompt",
    "MusicConfigPromptPayload",
    "PadStyle",
    "Palette",
    "PaletteColor",
    "PhraseLengthBars",
    "RhythmStyle",
    "RootNote",
    "SpaceLabel",
    "StepBiasLabel",
    "StereoLabel",
    "SwingLabel",
    "SyncopationLabel",
    "TempoLabel",
    "TensionCurve",
    "TextureStyle",
    "WeightLabel",
    # Schema utilities
    "repair_palette_duplicates",
    "schema_hash",
    "schema_signature",
    # Prompt constants
    "ROLE_MUSIC_EXPERT",
    "ROLE_SOUND_DESIGNER",
    "TASK_GENERATE_CONFIG",
    "TASK_JUSTIFICATION_FIRST",
    "TASK_USE_EXAMPLES",
    "PALETTE_REQUIREMENTS",
    "OUTPUT_JSON_ONLY",
    "OUTPUT_MATCH_SCHEMA",
    "OUTPUT_USE_ENUMS",
    "OUTPUT_USE_EXAMPLE_KEYS",
    "STYLE_AMBIENT",
    "STYLE_JUSTIFICATION_CONCISE",
    # Prompt builders
    "build_expressive_prompt",
    "build_inference_prompt",
    "build_litellm_prompt",
    "build_music_prompt",
    "build_training_prompt",
]
