"""Schema for generating music configuration payloads from vibe text.

This module re-exports shared schema definitions from common.music_schema
to maintain backwards compatibility for data_work consumers.
"""

from __future__ import annotations

# Re-export everything from common for backwards compatibility
from common import (
    MAX_LONG_FIELD_CHARS,
    MAX_TITLE_CHARS,
    MAX_TITLE_WORDS,
    PALETTE_COLOR_DESC,
    PALETTE_DESC,
    PALETTE_WEIGHT_DESC,
    PALETTE_WEIGHT_ORDER,
    PALETTES_DESC,
    PROMPT_DESC,
    PROMPT_REGISTER_MAX,
    PROMPT_REGISTER_MIN,
    AccentStyle,
    AttackStyle,
    BassStyle,
    BrightnessLabel,
    CadenceLabel,
    ChordChangeLabel,
    ChordExtensions,
    ChromaticLabel,
    DensityLevel,
    EchoLabel,
    GrainStyle,
    HarmonyStyle,
    HumanFeelLabel,
    MelodyDensityLabel,
    MelodyEngine,
    MelodyStyle,
    ModeName,
    MotifRepeatLabel,
    MotionLabel,
    MusicConfigPrompt,
    MusicConfigPromptPayload,
    PadStyle,
    Palette,
    PaletteColor,
    PhraseLengthBars,
    RhythmStyle,
    RootNote,
    SpaceLabel,
    StepBiasLabel,
    StereoLabel,
    SwingLabel,
    SyncopationLabel,
    TempoLabel,
    TensionCurve,
    TextureStyle,
    WeightLabel,
    repair_palette_duplicates,
    schema_hash,
    schema_signature,
)

__all__ = [
    "MAX_LONG_FIELD_CHARS",
    "MAX_TITLE_CHARS",
    "MAX_TITLE_WORDS",
    "PALETTE_COLOR_DESC",
    "PALETTE_DESC",
    "PALETTE_WEIGHT_DESC",
    "PALETTE_WEIGHT_ORDER",
    "PALETTES_DESC",
    "PROMPT_DESC",
    "PROMPT_REGISTER_MAX",
    "PROMPT_REGISTER_MIN",
    "AccentStyle",
    "AttackStyle",
    "BassStyle",
    "BrightnessLabel",
    "CadenceLabel",
    "ChordChangeLabel",
    "ChordExtensions",
    "ChromaticLabel",
    "DensityLevel",
    "EchoLabel",
    "GrainStyle",
    "HarmonyStyle",
    "HumanFeelLabel",
    "MelodyDensityLabel",
    "MelodyEngine",
    "MelodyStyle",
    "ModeName",
    "MotifRepeatLabel",
    "MotionLabel",
    "MusicConfigPrompt",
    "MusicConfigPromptPayload",
    "PadStyle",
    "Palette",
    "PaletteColor",
    "PhraseLengthBars",
    "RhythmStyle",
    "RootNote",
    "SpaceLabel",
    "StepBiasLabel",
    "StereoLabel",
    "SwingLabel",
    "SyncopationLabel",
    "TempoLabel",
    "TensionCurve",
    "TextureStyle",
    "WeightLabel",
    "repair_palette_duplicates",
    "schema_hash",
    "schema_signature",
]
